version: '3.2'

services:
  nginx:
    image: nginx:latest
    # маршрутизируем порты
    ports:
      - "80:80"
      - "443:443"
    # монтируем директории, слева директории на основной машине, справа - куда они монтируются в контейнере
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d
      - ./:/app
    networks:
      - internal

  php:
    build:
      context: ./docker
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./:/app
    working_dir: /app
    environment:
      XDEBUG_CONFIG: "client_host=192.168.235.1 client_port=9000"
      PHP_IDE_CONFIG: "serverName=Docker"
    networks:
      - internal

  pg:
    image: postgres:13-alpine
    volumes:
      - ./var/database/pgsql/data:/var/lib/postgresql/data
      - .:/app
    environment:
      - POSTGRES_PORT=5432
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    restart: always
    working_dir: /app
    ports:
      - 5432:5432
    networks:
      - internal

networks:
  internal:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.235.0/28